on:
  workflow_dispatch: 
jobs:
  upload-production-release-1gp:
    name: "Upload Production Release (1GP)"
    uses: SFDO-Community/standard-workflows/.github/workflows/production-1gp.yml@main
    secrets:
      packaging-org-auth-url: '${{ secrets.PACKAGING_ORG_AUTH_URL }}'
      dev-hub-auth-url: '${{ secrets.DEV_HUB_AUTH_URL }}'
